### ISSUE TITLE
Create ReadMe file

### ISSUE THREAD

**Issue by vicentepedro** [alexalm4190/Mask_RCNN-Vizzy_Hand#4]
Hi @alexalm4190 

You should create a readme file or wiki page for the repo explaining:
- [x] the general purpose of the repo
- [x] how to train the model (including how to prepare the data) 
- [x] how to test the model
- [x] include also some examples of the model working on the test set

Best,
Pedro

**Comment by alexalm-mf** [comment]
Hi @vicentepedro 

Thanks for pointing out the issue. I've added the README file with all your specs. I will close the issue now.

Kind regards,
Alexandre
